# Generated by Django 5.1.1 on 2024-10-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100, null=True)),
                ('book_author', models.CharField(max_length=100, null=True)),
                ('book_image', models.ImageField(upload_to='Media/Book_Image')),
                ('published_date', models.DateField(max_length=20, null=True)),
            ],
        ),
    ]
